### ISSUE TITLE
Errors in readme

### ISSUE THREAD

**Issue by isaac-ward** [RichardPienaar/MusicVideoGenerator#1]
**USEAGE** -> **USAGE**

How does **is** do it? -> How does **it** do it?

MusicVideoGenerator.py -songName [song.wav] -bpm [int] --output [outputPrefix] --dynamic [True/False] -> **python** MusicVideoGenerator.py -songName [song.wav] -bpm [int] --output [outputPrefix] --dynamic [True/False]

**Comment by isaac-ward** [comment]
SETTUP -> SET UP

**Comment by RichardPienaar** [comment]
Thanks!
